= TD1 : Requêtez-les tous !
:toc: left

```

                               ,'"`.,./.
                             ,'        Y',"..
                           ,'           \  | \
                          /              . |  `
                         /               | |   \
            __          .                | |    .
       _   \  `. ---.   |                | j    |
      / `-._\   `Y   \  |                |.     |
     _`.    ``    \   \ |..              '      |,-'""7,....
     l     '-.     . , `|  | , |`. , ,  /,     ,'    '/   ,'_,.-.
     `-..     `-.  : :     |/ `   ' "\,' | _  /          '-'    /___
      \""' __.,.-`.: :        /   /._    l'.,'
       `--,   _.-' `".           /__ `'-.' '         .
       ,---..._,.--"""""""--.__..----,-.'   .  /    .'   ,.--
       |                          ,':| /    | /     ;.,-'--      ,.-
       |     .---.              .'  :|'     |/ ,.-='"-.`"`' _   -.'
       /    \    /               `. :|--.  _L,"---.._        "----'
     ,' `.   \ ,'           _,     `''   ``.-'       `-  -..___,'
    . ,.  .   `   __     .-'  _.-           `.     .__    \
    |. |`        "  ;   !   ,.  |             `.    `.`'---'
    ,| |C\       ` /    | ,' |(]|            -. |-..--`
   /  "'--'       '      /___|__]        `.  `- |`.
  .       ,'                   ,   /       .    `. \
    \                      .,-'  ,'         .     `-.
     x---..`.  -'  __..--'"/"""""  ,-.      |   |   |
    / \--._'-.,.--'     _`-    _. ' /       |     -.|
   ,   .   `-..__ ...--'  _,.-' | `   ,.-.  ;   /  '|
  .  _,'         '"-----""      |    `   | /  ,'    ;
  |-'  .-.    `._               |     `._// ,'     /
 _|    `-'   _,' "`--.._________|        `,'    _ /.
//\   ,-._.'"/\__,.   _,"     /_\__/`. /'.-.'.-/_,`-' 

```

== Liens utiles

* https://www.mongodb.com/docs/manual


== Setup

Installation locale de `mongodb-community`

=== Windows

==== Installation

* `mongod` (démon)

https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows-unattended/#install-mongodb-community-edition

* `mongosh` (CLI)

https://www.mongodb.com/try/download/shell

==== Lancement / arrêt démon

Le lancement / arrêt du service se fait par les services Windows, proposé lors de l'installation du `*.msi`

=== MacOS

==== Installation

Prérequis https://brew.sh/[`homebrew`]

* `mongod` (démon) + `mongosh` (CLI)

https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#installing-mongodb-7.0-edition-edition

==== Lancement / arrêt démon

https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#run-mongodb-community-edition

=== MongoDB Compass (GUI)

https://www.mongodb.com/try/download/compass

=== Vérification de la connexion

```
$ mongosh
```

== Import des données

NOTE: L'option `-d` permet d'importer dans une nouvelle base crée à la volée, nommée `test`

```
$ mongoimport -d test -c pokemons --jsonArray ./datasets/pokemons.json
```

== TD 

=== Première connection

* Connectez-vous à votre service local, par défaut

```
$ mongosh
```

est équivalent à

```
$ mongosh "mongodb://localhost:27017"
```

* Listez la base de données en cours d'utisation

```
db
```

* Listez toutes les bases de données

```
show dbs
```

* Définissez la base de données dans laquelle nous venons d'importer les pokémons,

```
use test
```