= TD3 : Pipelines d'Agrégation
:toc: left
:icons: font
:imagesdir: images
:data-uri:

== Exercices

NOTE: Base de données `sample_mflix`, collection `movies`

=== q1

Calculez le top 10 des réalisateurs (`directors`) par nombre de films réalisés

=== q2

Calculez la note moyenne IMDB par classement (`rated`)

=== q3

Calculez le nombre de diffusion (`runtime`) moyen des films par pays

== Exercices notés

NOTE: Pour toutes les questions, vous pouvez vous aider sans problème de la documentation officielle https://www.mongodb.com/docs/manual/indexes, et de tout autre lien que vous estimez utile

IMPORTANT: Renseignez le pseudo unique suivant afin de garantir votre anonymat sur `Quiziniere.com` lorsque vous soumettrez votre copie

[cols="1,1"]
|===
|Nom |Pseudo

|AFIRI Driss
|`jYvfdE`

|BERTHELOT Leane
|`IuG7ZA`

|CHARASSON Gabin
|`DqO9T3`

|COLETTE Eotim
|`LTUYH9`

|CONDE Alpha Abdoulaye
|`udJaxs`

|DACCACHE Christian
|`37rdmJ`

|FAUVEAU Jérémie
|`hO9UHZ`

|FEUTRIER Mélina
|`TscXl0`

|GINESTE Pierre
|`Da7zhX`

|LAFAYE Alexis
|`ie9yML`

|LAINE Victor
|`6vNNah`

|LAMTIOUI Sami
|`LNjIOt`

|LAPLACE Tom
|`7ZJJoU`

|LEONELLI Marc-Antoine
|`DGsEro`

|PIN Matthieu
|`WGOdDh`

|PREVOT Nicolas
|`cNzbYa`

|ROUX Lucie
|`BR6oh8`

|SEGNI Maha
|`I0nFGV`

|SENOUSSA Ilyas
|`5G9FTL`

|SERVANT Matthias
|`x9jFju`

|SOHIER Jonathan
|`WmC1P5`
|=== 

* Répondez aux questions suivantes *notées* sur `Quiziniere.com` avec le lien fourni lors du cours :

https://www.quiziniere.com/diffusions/D9AZD7