= Plan de cours : {lecture}
Nicolas COMET <nicolas.comet@gmail.com>
:lecture: MongoDB, Optimisations NoSQL
:level: M2 Développement
:year: 2024-2025
:numbered:

[.metadata]
Formateur : {author}, {email}

Année scolaire : *{year}*

Public : *{level}*

== Pré-requis

* Un ordinateur et un connection internet
* Connaissances basiques des bases de données relationnelles

== Volume horaire

35h

== Objectifs de formation

En situation professionnelle, les apprenants seront capables de comprendre le fonctionnement de la base de données NoSQL MongoDB, de son indexation. Ils seront capables de diagnostiquer les problèmes de performance et d'y remédier.

Ils sauront installer et paramétrer un cluster et configurer la réplication ou le sharding de manière optimale afin de prévoir les montées en charge.

== Objectifs pédagogiques

=== MongoDB par la pratique

Les apprenants, à l'issue de la formation seront capables de :

* Comprendre la méthodologie de modélisation de données de la base NoSQL document MongoDB
* Savoir créer des index efficaces pour optimiser les requêtes
* Diagnostiquer un manque ou soucis d'indexation à la source de problèmes de performances
* Concevoir des requêtes complexes (statistiques, BI, jointures)

=== Architecture des clusters

Les apprenants, à l'issue de la formation seront à même de :

* Définir une architecture de cluster(s) dimensionnée aux besoins
* Comprendre les differentes stratégies de mise à l'échelle des clusters, et leurs implications
* Diagnostiquer en tant qu'administrateur·ice·s la cause d'une eventuelle congestion d'infrastructure

== Synopsis de la formation

[%header,cols="1,2,20"] 
|===
|
|Durée
|Thématique de la session

|1
|3h
|Brise glace. Introduction à MongoDB, différence entre ACID/BASE, relationnel et document.

|2
|3h
|Installation des outils locaux, familiarisation avec le shell `mongosh` & Compass, premières requêtes.

|3
|3h
|Les différents types d'index, leurs implications, bonnes pratiques. Analyse des index: `explain`, `hint`. Comment interpréter et optimiser.

|4
|3h
|TD en groupe : Rapide intro : Artchitectures Hexagonales, Application backend de mise en pratique avec MongoDB

|5
|3h
|Principes de modélisation de données (normalisation, dénormalisation)

|6
|3h
|Pipeline d'aggrégation, `lookup`

|7
|3h
|Correction travail modélisation, Architecture et déploiement des clusters, bonne pratiques: working set, mémoire, disque

|8
|3h
|Réplication, sharding : mise à l'échelle horizontale vs. Mise à l'échelle verticale

|9
|3h
|Profilage & statistiques avancées: `mongotop`, `mongostat`

|10
|3h
|Évaluation finale
|===

== Modalités d'évaluation

Différents moyens mis en œuvre pour s'assurer de la bonne progression des apprenants sous la forme d'évaluation formative:

* TDs pendant certaines sessions (requêtage, index, application utilisant un driver, modélisation, architecture des clusters)

Deux évaluations sommatives pour certifier les compétences acquises des apprenants:

* Cas d'étude / devoir : migration d'une base de données relationnelle vers MongoDB, d'un schéma existant vers une modélisation complète et performante, argumentée. Par groupes de 2 apprenants.
* Projet initié en cours lors de la dernière session, puis finie par groupes de deux : Application backend `Kotlin` `Ktor` `MongoDB` : gestion de parkings