= Plan de cours : {lecture}
Nicolas COMET <nicolas.comet@gmail.com>
:lecture: MongoDB, Optimisations NoSQL
:level: M2 Développement
:year: 2023-2024

[.metadata]
{author}

{level}, Année scolaire {year}

== Pré-requis

Un ordinateur et un connection internet

== Volume horaire

35h

== Objectifs de formation

En situation professionnelle, les apprenants seront capables de comprendre le fonctionnement de la base de données NoSQL MongoDB, de son indexation. Ils seront capables de diagnostiquer les problèmes de performance et d'y remédier.

Ils sauront installer et paramétrer un cluster et configurer la réplication ou le sharding de manière optimale afin de prévoir les montées en charge.

== Objectifs pédagogiques

TODO

== Synopsis de la formation

[%header,cols="1,2,20"] 
|===
|
|Durée
|Thématique de la session

|1
|3h
|Brise glace. Introduction à MongoDB, différence entre ACID/BASE, relationnel et document.

|2
|3h
|Installation des outils locaux, familiarisation avec le shell `mongosh` & Compass.

|3
|3h
|Les différents types d'index, leurs implications, bonnes pratiques.

|4
|3h
|Analyse des index: `explain`, `hint`. Comment interpréter et optimiser.

|5
|3h
|Principes de modélisation de données (normalisation, dénormalisation)

|6
|3h
|Architecture et déploiement des clusters, bonne pratiques: working set, mémoire, disque

|7
|3h
|Sharding, mise à l'échelle horizontale, bonne utilisation

|8
|3h
|Réplication, mise à l'échelle verticale

|9
|3h
|Profilage & statistiques avancées: `mongotop`, `mongostat`

|10
|3h
|Évaluation finale
|===

== Modalités d'évaluation

Différents moyens mis en œuvre pour s'assurer de la bonne progression des apprenants sous la forme d'évaluation formative:

* TDs pendant certaines sessions (requêtage, index, modélisation, architecture des clusters)

Deux évaluations sommatives pour certifier les compétences acquises des apprenants:

* Cas d'étude / devoir : migration d'une base de données relationnelle vers MongoDB, d'un schéma existant vers une modélisation complète et performante, argumentée. Par groupes de 2 apprenants.
* Réalisation en temps limité (évaluation finale) lors de la dernière session: diagnostiquer les raisons de sous-performance d'une architecture existante. Remédier à ses soucis grâce à un plan d'action décrit et argumenté.